### ISSUE TITLE
考试答案错误

### ISSUE THREAD

**Issue by Garfield** [hsmustard/youxueyuan#2]
我通过fiddler抓包工具获取到考试页面加载时的题目数据，通过你这提供的接口去查询答案，然后提交考试，却只有38-40分，很难受，不知道哪里错误了，求指教

**Comment by hsmustard** [comment]
这个接口获取考试题目答案没试过，我是用练习题来测试的

**Comment by yhzl-yk** [comment]
请问有智慧树的查题工具吗

**Comment by Garfield** [comment]
接口里面有

**Comment by hsmustard** [comment]
> 请问有智慧树的查题工具吗

我没有用过 智慧树 不过你可以尝试抓包看一下，有没有通过接口获取答案的情况

**Comment by yhzl-yk** [comment]
> 接口里面有

可以私发分享下吗?研究了一会，不会很懂
