### ISSUE TITLE
这个答案的接口是怎么获取的?

### ISSUE THREAD

**Issue by q6378561** [hsmustard/youxueyuan#3]
大佬帮忙排忧解难一下,我还自己写了个获取题库答案自动匹配来考试...结果题目ID全被改了,蛋疼

**Comment by yhzl-yk** [comment]
> 大佬帮忙排忧解难一下,我还自己写了个获取题库答案自动匹配来考试...结果题目ID全被改了,蛋疼

请问你是用爬虫写的吗
